# Generated by Django 4.1.6 on 2023-02-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_code_user_is_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
