# Generated by Django 4.1.6 on 2023-02-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersjwt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwtuser',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jwtuser',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jwtuser',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
