# Generated by Django 4.1.6 on 2023-02-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersjwt', '0003_alter_jwtuser_options_remove_jwtuser_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jwtuser',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='jwtuser',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='jwtuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
